spring:
  datasource:
    url: jdbc:mysql://mysql.od.com:3306/tb_stock?characterEncoding=utf-8
    username: shoping
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver

eureka:
  instance:
    prefer-ip-address: false
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8888/eureka



